version: '3.8'

services:

  # frontend:
    #   build:
    #     context: ./frontend
    #   ports:
    #     - "4200:4200"  
    #   depends_on:
    #     - tasks-service
    #     - projects-service
    #     - users-service
    #   networks:
    #     - app-network
  notifications-service:
    build:
      context: ${NOTIFICATIONS_SERVICE_PATH}
      dockerfile: Dockerfile
    hostname: ${NOTIFICATIONS_SERVICE_NAME}
    ports:
      - "${NOTIFICATIONS_SERVICE_PORT}:${NOTIFICATIONS_SERVICE_INTERNAL_PORT}"
    environment:
      - CASS_DB=${CASS_DB}
      - CASSANDRA_CONTACT_POINTS=${CASSANDRA_CONTACT_POINTS}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
    networks:
      - app-network
    depends_on:
      - cassandra
    restart: always
    volumes: 
      - ./backend/notifications-service/logs:/app/logs
  
  cassandra:
    image: cassandra:4.1
    container_name: ${CASSANDRA_NAME}
    hostname: ${CASSANDRA_NAME}
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    environment:
      - CASSANDRA_CLUSTER_NAME=TrelloCluster
      - CASSANDRA_NUM_TOKENS=256
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local;"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  tasks-service:
    build:
      context: ./backend    
      dockerfile: tasks-service/Dockerfile
    hostname: ${TASKS_SERVICE_NAME}
    ports:
      - "${TASKS_SERVICE_PORT}:${TASKS_SERVICE_INTERNAL_PORT}"
    environment:
      - MONGO_TASKS_URI=${MONGO_TASKS_URI}
      - WORKFLOW_SERVICE_URL=${WORKFLOW_SERVICE_URL}
      - LOG_PATH=/app/logs/tasks.log
      - LOG_LEVEL=debug 
    depends_on:
      - mongo-tasks
    networks:
      - app-network
    restart: on-failure
    volumes: 
      - ./backend/tasks-service/logs:/app/logs



  projects-service:
    build:
      context: ./backend    
      dockerfile: projects-service/Dockerfile
    hostname: ${PROJECTS_SERVICE_NAME}
    ports:
      - "${PROJECTS_SERVICE_PORT}:${PROJECTS_SERVICE_INTERNAL_PORT}"
    environment:
      - MONGO_PROJECTS_URI=${MONGO_PROJECTS_URI}
    depends_on: 
      - mongo-projects
    networks:
      - app-network
    restart: on-failure
    volumes:
      - ./backend/projects-service/logs:/app/logs

  users-service:
    build:
      context: ./backend             
      dockerfile: users-service/Dockerfile
    hostname: ${USERS_SERVICE_NAME}
    ports:
      - "${USERS_SERVICE_PORT}:${USERS_SERVICE_INTERNAL_PORT}"
    environment:
      - MONGO_USERS_URI=${MONGO_USERS_URI}
    depends_on:
      - mongo-users
    volumes:
      - ./backend/blacklist.txt:/app/blacklist.txt
      - ./backend/users-service/logs:/app/logs
    networks:
      - app-network

  workflow-service:
    build:
      context: ./backend
      dockerfile: workflow-service/Dockerfile
    hostname: ${WORKFLOW_SERVICE_NAME}
    ports:
      - "${WORKFLOW_SERVICE_PORT}:${WORKFLOW_SERVICE_INTERNAL_PORT}"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      - neo4j
    networks:
      - app-network
    restart: on-failure
    volumes:
      - ./backend/workflow-service/logs:/app/logs


  api-composer-service:
    build:
      context: ./backend
      dockerfile: api-composer-service/Dockerfile
    hostname: ${COMPOSER_SERVICE_NAME}
    ports:
      - "${COMPOSER_SERVICE_PORT}:${COMPOSER_SERVICE_INTERNAL_PORT}"
    networks:
      - app-network
    depends_on:
      - tasks-service
      - workflow-service
    restart: on-failure


  api_gateway:
    build:
      context: ${GATEWAY_PATH}
      dockerfile: Dockerfile
    container_name: ${GATEWAY_NAME}
    restart: on-failure
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    # depends_on:
    #   - tasks-service
    #   - projects-service
    #   - users-service
    networks:
      - app-network

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   
      - "7687:7687"   
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

  mongo-tasks:
    image: mongo:latest
    container_name: ${MONGO_TASKS_NAME}
    hostname: ${MONGO_TASKS_NAME}
    ports:
      - "${MONGO_TASKS_PORT}:${MONGO_TASKS_INTERNAL_PORT}"
    volumes:
      - mongo-tasks-data:/data/db
    networks:
      - app-network

  mongo-projects:
    image: mongo:latest
    container_name: ${MONGO_PROJECTS_NAME}
    hostname: ${MONGO_PROJECTS_NAME}
    ports:
      - "${MONGO_PROJECTS_PORT}:${MONGO_PROJECTS_INTERNAL_PORT}"
    volumes:
      - mongo-projects-data:/data/db
    networks:
      - app-network

  mongo-users:
    image: mongo:latest
    container_name: ${MONGO_USERS_NAME}
    hostname: ${MONGO_USERS_NAME}
    ports:
      - "${MONGO_USERS_PORT}:${MONGO_USERS_INTERNAL_PORT}"
    volumes:
      - mongo-users-data:/data/db
    networks:
      - app-network

volumes:
  mongo-tasks-data:
    driver: local
  mongo-projects-data:
    driver: local
  mongo-users-data:
    driver: local
  neo4j-data:
    driver: local


networks:
  app-network:
    name: app-network
    driver: bridge
