version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "4200:4200"  
  #   depends_on:
  #     - tasks-service
  #     - projects-service
  #     - users-service
  #   networks:
  #     - app-network

  tasks-service:
    build:
      context: ./backend/tasks-service  
    ports:
      - "8002:8000"
    environment:
      - MONGO_TASKS_URI=mongodb://mongo-tasks:27017/tasks_db  
    depends_on:
      - mongo-tasks
    networks:
      - app-network

  projects-service:
    build:
      context: ./backend/projects-service  
    ports:
      - "8003:8080" 
    environment:
      - MONGO_PROJECTS_URI=mongodb://mongo-projects:27017/projects_db  
    depends_on:
      - mongo-projects
    networks:
      - app-network

  users-service:
    build:
      context: ./backend/users-service  
    ports:
      - "8001:8080"  
    env_file:
      - ./backend/users-service/.env
    environment:
      - MONGO_USERS_URI=mongodb://mongo-users:27017/users_db 
    depends_on:
      - mongo-users
    networks:
      - app-network

  mongo-tasks:
    image: mongo:latest
    container_name: mongo-tasks
    ports:
      - "27018:27017"  
    volumes:
      - mongo-tasks-data:/data/db 
    networks:
      - app-network

  mongo-projects:
    image: mongo:latest
    container_name: mongo-projects
    ports:
      - "27019:27017"
    volumes:
      - mongo-projects-data:/data/db 
    networks:
      - app-network

  mongo-users:
    image: mongo:latest
    container_name: mongo-users
    ports:
      - "27020:27017"
    volumes:
      - mongo-users-data:/data/db 
    networks:
      - app-network

volumes:
  mongo-tasks-data:
    driver: local
  mongo-projects-data:
    driver: local
  mongo-users-data:
    driver: local

networks:
  app-network:
    driver: bridge
